### ISSUE TITLE
Error with julia v1.11 due to BinaryProvider dependency.

### ISSUE THREAD

**Issue by hellemo** [kdheepak/FIGlet.jl#11]
I get an error when trying to install with julia v.1.11 (see discourse discussion below).

https://discourse.julialang.org/t/mysterious-binaryprovider-error-when-installing-figlet/122279/1

`FIGlet` seems to work with the current master, so I guess a new release would be enough to fix this issue?

**Comment by kdheepak** [comment]
I made a new release in this commit: https://github.com/kdheepak/FIGlet.jl/commit/1e674df6c47fe1ac28453f70e99494657281bdb4
