### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by BeastyBlacksmith** [kdheepak/FIGlet.jl#3]
```julia
FIGlet.render.(Ref("julia"), FIGlet.availablefonts()[491] )
ERROR: Not implemented yet.
```

**Comment by BeastyBlacksmith** [comment]
also `447, 450, 486`

**Comment by kdheepak** [comment]
Right to left fonts are not implemented right now. I'll look into this, it should be straightforward.

**Comment by kdheepak** [comment]
Thanks for reporting the numbers of all the fonts that failed!

I verified that those are the only ones in the collection that fail:

```julia
julia> for font in FIGlet.availablefonts()
       try
       iob = IOBuffer()
       FIGlet.render(iob, "julia", font)
       catch
       @show font
       end
       end
┌ Warning: Received unknown header attributes: `("34", "63", "HIKE")`.
└ @ FIGlet ~/GitRepos/FIGlet.jl/src/FIGlet.jl:86
font = "ivrit"
font = "jerusalem"
font = "mirror"
font = "mshebrew210"
```

**Comment by kdheepak** [comment]
You should be able to get the latest version now and have this work:

https://github.com/kdheepak/FIGlet.jl/releases/tag/v0.2.0

![Screen Shot 2019-10-24 at 5 08 47 PM](https://user-images.githubusercontent.com/1813121/67531760-25637580-f681-11e9-8c36-a6c066969f36.png)
